# Create numpy array using python "array like" data types

In [66]:
import numpy as np


In [67]:
print(np.__version__)

1.20.2


In [68]:
my_list=[-17,0,4,5,9]

my_array_from_list=np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

Elementry Multiplication

In [69]:
list_1=[1,2,3]
a=list_1*5
a

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [70]:
my_array_from_list*10


array([-170,    0,   40,   50,   90])

In [71]:
my_tuple=(14, -3.54, 5+7j)
np.array(my_tuple)

array([14.  +0.j, -3.54+0.j,  5.  +7.j])

# Difference between python and numpy data structure

In [72]:
my_tuple*5

(14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j),
 14,
 -3.54,
 (5+7j))

In [73]:
np.array(my_tuple)*5

array([ 70.  +0.j, -17.7 +0.j,  25. +35.j])

#  Intrinsic NumPy array creation using numpy's method

In [16]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [18]:
len(np.arange(10,23))

13

In [19]:
my_range_array=np.arange(10,23)
my_range_array.size

13

In [20]:
np.arange(10,23,5)

array([10, 15, 20])

In [21]:
np.arange(25, step=5)

array([ 0,  5, 10, 15, 20])

# numpy.matrix.transpose

In [22]:
a = np.array([[1, 2], [3, 4],[5,6]]).T
a

array([[1, 3, 5],
       [2, 4, 6]])

In [23]:
a.transpose()

array([[1, 2],
       [3, 4],
       [5, 6]])

# linspace(), zeros(), ones(), and NumPy data types

In [43]:
np.linspace(5 , 15 , 5 ,retstep=True)

(array([ 5. ,  7.5, 10. , 12.5, 15. ]), 2.5)

In [46]:
my_linspace=np.linspace(0,360,10, retstep=True)
a=np.arange(0,360,10)
my_linspace

(array([  0.,  40.,  80., 120., 160., 200., 240., 280., 320., 360.]), 40.0)

In [30]:
print(a)
my_linspace

[[1 3 5]
 [2 4 6]]


NameError: name 'my_linspace' is not defined

In [29]:
my_linspace[1]

NameError: name 'my_linspace' is not defined

# Zeros Function

In [28]:
np.zeros(5)

AttributeError: module 'random' has no attribute 'zeros'

# Ones Function

In [75]:
 np.ones(5)

array([1., 1., 1., 1., 1.])

In [74]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5,4))

In [ ]:
np.zeros((3,3))

In [55]:
np.zeros(5, dtype='int32')

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(5)

# Slicing Array

In [82]:
my_vector=np.array([-17,-4,0,2,21,37,105])
(my_vector)

array([-17,  -4,   0,   2,  21,  37, 105])

In [83]:
my_vector[0]

-17

In [84]:
my_vector[0]=-102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [85]:
my_vector[-3]

21

In [86]:
my_vector[105]

IndexError: index 105 is out of bounds for axis 0 with size 7

In [87]:
305%7

4

In [88]:
my_vector[305%7]


21

In [89]:
my_vector.size

7

In [90]:
my_vector[305%my_vector.size]

21

# Two Dimensional Array

In [91]:
my_array=np.arange(1,36).reshape(7,5)
# my_array.shape=(7,5)
my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [92]:
my_array[2]

array([11, 12, 13, 14, 15])

In [93]:
my_array[-2]

array([26, 27, 28, 29, 30])

In [94]:
my_array[5][2]

28

In [95]:
row=5
column=2
my_array[row,column]

28

In [96]:
my_array[5][2]

28

# Three Dimensional Array

In [97]:
my_3D_array=np.arange(70).reshape(2,7,5)
# my_3D_array.shape=(2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [98]:
my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [99]:
my_3D_array[1,3]

array([50, 51, 52, 53, 54])

In [ ]:
my_3D_array[1,3,2]

In [ ]:
my_3D_array[1,3,2]=1111
my_3D_array

In [ ]:
import numpy as np

# Boolean Mask Array

In [ ]:
my_vector=np.array([-17,-4,0,2,21,37,105])
my_vector

In [ ]:
zero_mode_7_mask=0==(my_vector%7)
zero_mode_7_mask

In [ ]:
sub_array=my_vector[zero_mode_7_mask]
sub_array

In [ ]:
sub_array[sub_array>0]

In [ ]:
 sub_array

# NumPy Logical Operators

In [58]:
my_vector=np.array([-17,-4,0,2,21,37,105])
mod_test=0==(my_vector%7)
possitive_test=my_vector > 0
print(mod_test)
print(possitive_test)
combined_mask=np.logical_and(mod_test, possitive_test)
combined_mask

[False False  True False  True False  True]
[False False False  True  True  True  True]


array([False, False, False, False,  True, False,  True])

In [57]:
my_vector[[False, False, False, False,  True, False,  True]]

array([ 21, 105])

# Broadcasting : It defines that how numpy perform operations with an array of different sizes

In [ ]:
my_3D_array=np.arange(70)
my_3D_array.shape=(2,7,5)
my_3D_array

In [ ]:
#Shape
my_3D_array.shape


In [ ]:
#Number of dimensions
my_3D_array.ndim

In [ ]:
#Size
my_3D_array.size

In [ ]:
#datatype for each elements
my_3D_array.dtype

In [ ]:
5*my_3D_array-2

In [ ]:
left_mat=np.arange(4).reshape((2,2))
print(left_mat)
right_mat=np.arange(4).reshape((2,2))
print(right_mat)

In [ ]:
np.inner(left_mat, right_mat)

In [ ]:
np.dot(left_mat, right_mat)


# Operation along axis: Broadcasting along particular axis

In [100]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [ ]:
my_3D_array.sum()

In [ ]:
my_2D_array=np.arange(15).reshape(3,5)
my_2D_array

In [ ]:
my_2D_array.sum(axis=0)

In [ ]:
my_2D_array.sum(axis=1)

In [ ]:
my_3D_array.sum(axis=2)

# Broadcasting Rules

In [101]:
my_2D_array=np.ones(35, dtype="int").reshape(7,5)*3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [102]:
my_random_2D_array=np.random.randn(7,5)
my_random_2D_array

array([[ 1.7667632 , -1.08604386,  0.86573701, -0.39141117, -1.47371184],
       [-0.03020628,  0.25357195, -1.4980143 , -1.40079555,  2.32508297],
       [ 0.10176192,  0.17486948,  0.25068131, -1.01098893, -0.51841007],
       [ 1.23594711,  0.20969922,  1.57194299,  1.62089044,  0.46887003],
       [-0.76845456, -0.74045686,  0.72321697, -1.8567966 , -0.67637991],
       [ 0.9177685 ,  0.72589046,  0.48742235,  0.76351226,  0.08580814],
       [-0.71737784, -0.03613952,  1.23876405, -1.95691623,  1.3765135 ]])

In [103]:
np.set_printoptions(precision=4)
my_3D_array*my_random_2D_array

array([[[   0.    ,   -1.086 ,    1.7315,   -1.1742,   -5.8948],
        [  -0.151 ,    1.5214,  -10.4861,  -11.2064,   20.9257],
        [   1.0176,    1.9236,    3.0082,  -13.1429,   -7.2577],
        [  18.5392,    3.3552,   26.723 ,   29.176 ,    8.9085],
        [ -15.3691,  -15.5496,   15.9108,  -42.7063,  -16.2331],
        [  22.9442,   18.8732,   13.1604,   21.3783,    2.4884],
        [ -21.5213,   -1.1203,   39.6404,  -64.5782,   46.8015]],

       [[  61.8367,  -39.0976,   32.0323,  -14.8736,  -57.4748],
        [  -1.2083,   10.3964,  -62.9166,  -60.2342,  102.3037],
        [   4.5793,    8.044 ,   11.782 ,  -48.5275,  -25.4021],
        [  61.7974,   10.6947,   81.741 ,   85.9072,   25.319 ],
        [ -42.265 ,  -41.4656,   41.2234, -107.6942,  -39.9064],
        [  55.0661,   44.2793,   30.2202,   48.1013,    5.4917],
        [ -46.6296,   -2.3852,   82.9972, -133.0703,   94.9794]]])

In [104]:
my_vector=np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [105]:
my_3D_array*my_vector

array([[[   0,    7,   28,   63,  112],
        [  -5,   42,   98,  168,  252],
        [ -10,   77,  168,  273,  392],
        [ -15,  112,  238,  378,  532],
        [ -20,  147,  308,  483,  672],
        [ -25,  182,  378,  588,  812],
        [ -30,  217,  448,  693,  952]],

       [[ -35,  252,  518,  798, 1092],
        [ -40,  287,  588,  903, 1232],
        [ -45,  322,  658, 1008, 1372],
        [ -50,  357,  728, 1113, 1512],
        [ -55,  392,  798, 1218, 1652],
        [ -60,  427,  868, 1323, 1792],
        [ -65,  462,  938, 1428, 1932]]])

In [106]:
import numpy as np
my_3d_array=np.array((2,5,5))
my_2d_array=np.random.randint((5,5))

my_3d_array*my_2d_array

ValueError: operands could not be broadcast together with shapes (3,) (2,) 